package report

import (
	"context"
	"crypto/sha256"
	"encoding/base64"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"

	"github.com/fuck-you-isp/fyisp/internal/model"
	"github.com/fuck-you-isp/fyisp/internal/store"
)

// checkStatic asserts the document is self-contained and CSP-safe.
func checkStatic(t *testing.T, html string) {
	t.Helper()
	lower := strings.ToLower(html)
	for _, bad := range []string{"<script", "javascript:", "http://", "https://", "<iframe", "<link", "<img", "<object", "<embed", "@import", "url("} {
		if strings.Contains(lower, bad) {
			t.Errorf("report contains %q", bad)
		}
	}
	if m := regexp.MustCompile(`(?i)\son[a-z]+\s*=`).FindString(html); m != "" {
		t.Errorf("event handler attribute %q", m)
	}
	if m := regexp.MustCompile(`(?i)\sstyle\s*=`).FindString(html); m != "" {
		t.Errorf("inline style attribute %q (not allowed by the CSP)", m)
	}
	styles := regexp.MustCompile(`(?s)<style>(.*?)</style>`).FindAllStringSubmatch(html, -1)
	if len(styles) != 1 {
		t.Fatalf("%d <style> elements, want 1", len(styles))
	}
	h := sha256.Sum256([]byte(styles[0][1]))
	if want := "'sha256-" + base64.StdEncoding.EncodeToString(h[:]) + "'"; !strings.Contains(CSP(), want) {
		t.Errorf("CSP %q does not allow the stylesheet (%s)", CSP(), want)
	}
	if !strings.Contains(html, `http-equiv="Content-Security-Policy" content="`) || !strings.Contains(CSP(), "default-src 'none'") {
		t.Error("no CSP meta tag")
	}
	if !strings.HasPrefix(html, "<!doctype html>") || !strings.HasSuffix(strings.TrimSpace(html), "</html>") {
		t.Error("not a complete document")
	}
}

func TestStructure(t *testing.T) {
	f := newFixture(t, 7, 5*time.Minute)
	html := f.build(t, f.deps(), Options{Title: "Evidence for Example ISP"})
	checkStatic(t, html)
	for _, want := range []string{
		`id="header"`, `id="summary"`, `id="outages"`, `id="charts"`, `id="traces"`, `id="notes"`, `id="footer"`,
		"<title>Evidence for Example ISP</title>",
		"Mon 14 Sep 2026 00:00 UTC", "(7d)",
		"AS64500 EXAMPLE-ISP",
		"Your ISP&#39;s network dropped packets on 6 of 7 days",
		"in 6 incidents",
		"Individual services",
		"The longest incident (ISP problem) started Sat 19 Sep 2026 19:00 UTC and lasted 45m",
		"Network path",
		"Common Services", // Discord's group: named by an incident
		"real loss: continues to the destination",
		"not real: router limits its replies",
		"Route changes",
		"The worst time of day was",
		"fyisp was measuring during",
		"Generated by fyisp",
		"All times are in UTC",
		publicNote,
		"<svg class=\"chart\"",
	} {
		if !strings.Contains(html, want) {
			t.Errorf("report lacks %q", want)
		}
	}
	// Groups without incidents or loss are in the overview only.
	if strings.Count(html, `<figure class="group">`) != 2 {
		t.Errorf("%d charts, want 2 (network path, common services)", strings.Count(html, `<figure class="group">`))
	}
	// Incidents appear in time order in the outage log.
	i1, i2 := strings.Index(html, "2026-09-14 10:00:00"), strings.Index(html, "2026-09-14 19:00:00")
	if i1 < 0 || i2 < 0 || i1 > i2 {
		t.Errorf("outage log order: service at %d, isp at %d", i1, i2)
	}
}

func TestRedaction(t *testing.T) {
	f := newFixture(t, 2, 5*time.Minute)
	secrets := []string{
		"192.168.", "100.64.", "10.0.0.1", gwRDNS, cgnatRDNS, edgeRDNS, hop4RDNS, secretNote, "SECRET-PRIVATE",
		"203.0.113.9", testVersion,
	}
	local := f.build(t, f.deps(), Options{})
	checkStatic(t, local)
	for _, s := range secrets {
		if s == "100.64." || s == "192.168." || s == "SECRET-PRIVATE" {
			continue
		}
		if !strings.Contains(local, s) {
			t.Errorf("local report lacks %q", s)
		}
	}
	pub := f.build(t, f.deps(), Options{Redact: true})
	checkStatic(t, pub)
	for _, s := range secrets {
		if strings.Contains(pub, s) {
			t.Errorf("redacted report contains %q", s)
		}
	}
	for _, want := range []string{"203.0.113.x", "198.51.100.4", farRDNS, publicNote, "private (hidden)", "[private address]", "redacted for sharing", "AS64500 EXAMPLE-ISP"} {
		if !strings.Contains(pub, want) {
			t.Errorf("redacted report lacks %q", want)
		}
	}
}

func TestEmptyRange(t *testing.T) {
	f := newFixture(t, 1, 15*time.Minute)
	from := f.from.Add(-30 * 24 * time.Hour)
	html := f.build(t, f.deps(), Options{From: from, To: from.Add(24 * time.Hour)})
	checkStatic(t, html)
	if n := strings.Count(html, "No data: fyisp has no measurements in this range."); n < 2 {
		t.Errorf("no-data notice shown %d times", n)
	}
	if strings.Contains(html, "<svg class=\"chart\"") || strings.Contains(html, "class=\"log\"") {
		t.Error("empty report has charts or an outage log")
	}
	// Bare deps: only a store, no profile.
	b, err := New(Deps{Store: store.NewFake()}).Build(context.Background(), Options{From: from, To: from.Add(time.Hour)})
	if err != nil {
		t.Fatal(err)
	}
	checkStatic(t, string(b))
	if !strings.Contains(string(b), "No data") || strings.Contains(string(b), `id="traces"`) || strings.Contains(string(b), `id="notes"`) {
		t.Error("bare report: want no data and no trace/notes sections")
	}
}

func TestBadRange(t *testing.T) {
	now := time.Now()
	if _, err := New(Deps{Store: store.NewFake()}).Build(context.Background(), Options{From: now, To: now.Add(-time.Hour)}); err == nil {
		t.Error("reversed range accepted")
	}
	if _, err := New(Deps{}).Build(context.Background(), Options{}); err == nil {
		t.Error("no store accepted")
	}
}

func TestOngoingIncidentAndDefaults(t *testing.T) {
	f := newFixture(t, 1, 15*time.Minute)
	f.incidents = append(f.incidents, model.Incident{ID: 99, Start: f.to.Add(-30 * time.Minute), Kind: model.VerdictLAN, Summary: "Your router is not answering."})
	html := f.build(t, f.deps(), Options{Now: func() time.Time { return f.to }, From: f.from, To: f.to})
	if !strings.Contains(html, "ongoing") || !strings.Contains(html, "Your home network") {
		t.Error("ongoing LAN incident not shown")
	}
	// Zero range: the last DefaultRange up to now.
	b, err := New(f.deps()).Build(context.Background(), Options{Now: func() time.Time { return f.to }})
	if err != nil || !strings.Contains(string(b), "(7d)") {
		t.Errorf("default range: err %v", err)
	}
}

func TestSize(t *testing.T) {
	if testing.Short() {
		t.Skip("slow")
	}
	f := newFixture(t, 7, 5*time.Minute)
	// Worst case: every group charted (lossy everywhere).
	var all []string
	for _, tg := range f.prof.Targets {
		all = append(all, tg.Name)
	}
	f.incidents = append(f.incidents, model.Incident{ID: 1000, Start: f.from.Add(time.Hour), End: f.from.Add(2 * time.Hour), Kind: model.VerdictService, Summary: "Many services failing.", Targets: all})
	for i := 0; i < 500; i++ {
		s := f.from.Add(time.Duration(i) * 17 * time.Minute)
		f.incidents = append(f.incidents, model.Incident{ID: int64(2000 + i), Start: s, End: s.Add(time.Minute), Kind: model.VerdictDNS, Summary: "Name lookups are failing."})
	}
	html := f.build(t, f.deps(), Options{})
	t.Logf("7-day report with every group charted: %d KB", len(html)>>10)
	if len(html) > 2<<20 {
		t.Errorf("report is %d bytes, want < 2 MB", len(html))
	}
	if !strings.Contains(html, "shortest of") {
		t.Error("outage log not capped")
	}
	// 48 h: the raw tier, up to ChartPoints per series.
	f2 := newFixture(t, 2, time.Minute)
	html = f2.build(t, f2.deps(), Options{})
	t.Logf("2-day report: %d KB", len(html)>>10)
	if len(html) > 2<<20 {
		t.Errorf("2-day report is %d bytes", len(html))
	}
}

// TestWriteSamples writes sample reports for manual review when
// FYISP_REPORT_OUT names a directory.
func TestWriteSamples(t *testing.T) {
	dir := os.Getenv("FYISP_REPORT_OUT")
	if dir == "" {
		t.Skip("FYISP_REPORT_OUT not set")
	}
	f := newFixture(t, 7, 5*time.Minute)
	f2 := newFixture(t, 1, time.Minute)
	for name, html := range map[string]string{
		"sample-7d.html":          f.build(t, f.deps(), Options{Title: "Evidence for Example ISP"}),
		"sample-7d-redacted.html": f.build(t, f.deps(), Options{Title: "Evidence for Example ISP", Redact: true}),
		"sample-1d.html":          f2.build(t, f2.deps(), Options{}),
		"sample-empty.html":       f.build(t, f.deps(), Options{From: f.from.Add(-60 * 24 * time.Hour), To: f.from.Add(-59 * 24 * time.Hour)}),
	} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(html), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}
