package main

import (
	"context"
	"fmt"
	"html"
	"math"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/fuck-you-isp/fyisp/internal/model"
	"github.com/fuck-you-isp/fyisp/internal/store"
	"github.com/fuck-you-isp/fyisp/internal/web"
)

// slowdown is the synthetic "evening slowdown": these targets run slower
// than their normal for the last 45 minutes of the backfill and live.
var slowdown = map[string]float64{"AWS-us-east-1": 2.4, "dev-GitHub": 1.8, "Discord": 1.6}

const slowFor = 45 * time.Minute

// slowSink multiplies the RTT of the slowdown targets from `since` on.
func slowSink(inner model.Sink, since time.Time) model.Sink {
	return model.SinkFunc(func(s model.Sample) {
		if f, ok := slowdown[s.Key.Target]; ok && !s.Lost && !s.Slot.Before(since) {
			s.RTT = time.Duration(float64(s.RTT) * f)
		}
		inner.Observe(s)
	})
}

// ---------- annotations ----------

// fakeNotes implements web.AnnotationStore in memory.
type fakeNotes struct {
	mu   sync.Mutex
	next int64
	m    map[int64]model.Annotation
}

func newFakeNotes(now time.Time, bf time.Duration) *fakeNotes {
	f := &fakeNotes{m: map[int64]model.Annotation{}}
	ctx := context.Background()
	add := func(at, end time.Time, text string, public bool) {
		_ = f.AddAnnotation(ctx, &model.Annotation{At: at, End: end, Text: text, Public: public})
	}
	add(now.Add(-slowFor), time.Time{}, "Evenings are slow again: GitHub pushes crawl", true)
	add(now.Add(-6*time.Minute), time.Time{}, "Zoom call with the team froze twice", false)
	if bf > 0 {
		_, isp, lan := windows(bf, now)
		add(isp.from.Add(time.Minute), time.Time{}, "Video call dropped (client demo)", false)
		add(isp.from, isp.to.Add(10*time.Minute), "ISP ticket #4471 opened; they blame \"maintenance\"", true)
		add(lan.from, time.Time{}, "Rebooted the router in the hallway", false)
	}
	return f
}

func (f *fakeNotes) AddAnnotation(_ context.Context, a *model.Annotation) error {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.next++
	now := time.Now()
	a.ID, a.Created, a.Updated = f.next, now, now
	f.m[a.ID] = *a
	return nil
}

func (f *fakeNotes) UpdateAnnotation(_ context.Context, a *model.Annotation) error {
	f.mu.Lock()
	defer f.mu.Unlock()
	old, ok := f.m[a.ID]
	if !ok {
		return web.ErrNotFound
	}
	a.Created, a.Updated = old.Created, time.Now()
	f.m[a.ID] = *a
	return nil
}

func (f *fakeNotes) DeleteAnnotation(_ context.Context, id int64) error {
	f.mu.Lock()
	defer f.mu.Unlock()
	if _, ok := f.m[id]; !ok {
		return web.ErrNotFound
	}
	delete(f.m, id)
	return nil
}

func (f *fakeNotes) Annotations(_ context.Context, from, to time.Time, publicOnly bool) ([]model.Annotation, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	var out []model.Annotation
	for _, a := range f.m {
		end := a.End
		if end.IsZero() {
			end = a.At
		}
		if a.At.After(to) || end.Before(from) || (publicOnly && !a.Public) {
			continue
		}
		out = append(out, a)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].At.Before(out[j].At) })
	return out, nil
}

// ---------- reports ----------

// fakeReports implements web.ReportSource: a stub builder (a small
// self-contained HTML page like the real report: inline CSS and SVG, no
// scripts) and an in-memory snapshot store.
type fakeReports struct {
	notes *fakeNotes
	inc   web.VerdictSource
	st    store.Reader

	mu   sync.Mutex
	m    map[string]model.ReportMeta
	body map[string][]byte
}

func newFakeReports(notes *fakeNotes, inc web.VerdictSource, st store.Reader) *fakeReports {
	return &fakeReports{notes: notes, inc: inc, st: st, m: map[string]model.ReportMeta{}, body: map[string][]byte{}}
}

func (f *fakeReports) Build(ctx context.Context, o web.ReportOptions) ([]byte, error) {
	var b strings.Builder
	esc := html.EscapeString
	tf := func(t time.Time) string { return t.Local().Format("Jan 2 15:04") }
	fmt.Fprintf(&b, `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>%s</title>
<style>
:root{color-scheme:light dark;--ink:#0b0b0b;--muted:#6f6e69;--bg:#fcfcfb;--line:#e1e0d9;--acc:#2a78d6;--bad:#cc2f2f}
@media (prefers-color-scheme:dark){:root{--ink:#fff;--muted:#898781;--bg:#1a1a19;--line:#2c2c2a;--acc:#3987e5;--bad:#e04848}}
body{margin:0 auto;max-width:880px;padding:24px 16px;font:14px/1.5 system-ui,sans-serif;color:var(--ink);background:var(--bg)}
h1{font-size:22px;margin:0 0 4px}h2{font-size:16px;margin:24px 0 8px;border-bottom:1px solid var(--line);padding-bottom:4px}
.m{color:var(--muted)}table{border-collapse:collapse;width:100%%}td,th{text-align:left;padding:4px 8px;border-bottom:1px solid var(--line)}
.tag{display:inline-block;font-size:11px;padding:0 8px;border-radius:9px;border:1px solid var(--line)}svg{width:100%%;height:auto}
</style></head><body>`, esc(o.Title))
	fmt.Fprintf(&b, `<h1>%s</h1><p class="m">%s – %s · generated by fyisp-webdev (sample report) · %s</p>`,
		esc(o.Title), tf(o.From), tf(o.To), map[bool]string{true: "redacted: no private addresses, public notes only", false: "includes private details"}[o.Redact])
	b.WriteString(`<h2>Outages</h2><table><tr><th>When</th><th>Kind</th><th>What happened</th><th>Peak loss</th></tr>`)
	var list []model.Incident
	if f.inc != nil {
		list, _ = f.inc.Incidents(ctx, o.From, o.To)
	}
	if len(list) == 0 {
		b.WriteString(`<tr><td colspan="4" class="m">No incidents in this range.</td></tr>`)
	}
	for _, in := range list {
		end := "ongoing"
		if !in.End.IsZero() {
			end = in.End.Local().Format("15:04")
		}
		fmt.Fprintf(&b, `<tr><td>%s – %s</td><td><span class="tag">%s</span></td><td>%s</td><td>%.0f%%</td></tr>`,
			tf(in.Start), end, esc(string(in.Kind)), esc(in.Summary), in.PeakLoss*100)
	}
	b.WriteString(`</table><h2>Latency (AWS-us-east-1, HTTPS)</h2>`)
	b.WriteString(f.sparkline(ctx, o.From, o.To))
	b.WriteString(`<h2>Notes</h2><ul>`)
	notes, _ := f.notes.Annotations(ctx, o.From, o.To, o.Redact)
	if len(notes) == 0 {
		b.WriteString(`<li class="m">No notes in this range.</li>`)
	}
	for _, n := range notes {
		fmt.Fprintf(&b, `<li>%s — %s</li>`, tf(n.At), esc(n.Text))
	}
	b.WriteString(`</ul>`)
	if !o.Redact {
		b.WriteString(`<h2>Network details</h2><p>Gateway 192.168.1.1 · ISP edge 96.120.88.105 (po-305-1210-rur01.fremont.ca.sfba.comcast.net)</p>`)
	}
	b.WriteString(`</body></html>`)
	return []byte(b.String()), nil
}

// sparkline draws one series as an inline SVG polyline.
func (f *fakeReports) sparkline(ctx context.Context, from, to time.Time) string {
	res, err := f.st.Panel(ctx, store.PanelQuery{Keys: []model.SeriesKey{{Target: "AWS-us-east-1", Kind: model.KindHTTPS}}, From: from, To: to, MaxPoints: 300})
	if err != nil || len(res.Series) == 0 {
		return `<p class="m">No data.</p>`
	}
	m := res.Series[0].Mean
	hi := 1.0
	for _, v := range m {
		if !math.IsNaN(float64(v)) {
			hi = math.Max(hi, float64(v))
		}
	}
	var pts []string
	for i, v := range m {
		if math.IsNaN(float64(v)) {
			continue
		}
		x := 800 * float64(i) / math.Max(1, float64(len(m)-1))
		pts = append(pts, fmt.Sprintf("%.1f,%.1f", x, 150-140*float64(v)/hi))
	}
	return fmt.Sprintf(`<svg viewBox="0 0 800 160" role="img" aria-label="latency"><rect width="800" height="160" fill="none" stroke="currentColor" stroke-opacity=".15"/><polyline fill="none" stroke="#3987e5" stroke-width="1.5" points="%s"/><text x="4" y="14" font-size="11" fill="currentColor" opacity=".6">%.0f ms</text></svg>`, strings.Join(pts, " "), hi)
}

func (f *fakeReports) SaveReport(_ context.Context, m model.ReportMeta, body []byte) error {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.m[m.ID], f.body[m.ID] = m, body
	return nil
}

func (f *fakeReports) Report(_ context.Context, id string) (model.ReportMeta, []byte, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	m, ok := f.m[id]
	if !ok {
		return m, nil, web.ErrNotFound
	}
	return m, f.body[id], nil
}

func (f *fakeReports) Reports(context.Context) ([]model.ReportMeta, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	out := make([]model.ReportMeta, 0, len(f.m))
	for _, m := range f.m {
		out = append(out, m)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Created.After(out[j].Created) })
	return out, nil
}

func (f *fakeReports) SetReportPublic(_ context.Context, id string, public bool) error {
	f.mu.Lock()
	defer f.mu.Unlock()
	m, ok := f.m[id]
	if !ok {
		return web.ErrNotFound
	}
	m.Public = public
	f.m[id] = m
	return nil
}

func (f *fakeReports) DeleteReport(_ context.Context, id string) error {
	f.mu.Lock()
	defer f.mu.Unlock()
	if _, ok := f.m[id]; !ok {
		return web.ErrNotFound
	}
	delete(f.m, id)
	delete(f.body, id)
	return nil
}

// seed stores a sample redacted report with a fixed ID (so its public
// link is stable across restarts with the same -secret).
func (f *fakeReports) seed(ctx context.Context, from, to time.Time) (string, error) {
	const id = "rsamplesampleaaaaaaaaaaaaa"
	body, err := f.Build(ctx, web.ReportOptions{From: from, To: to, Title: "ISP outage evidence (sample)", Redact: true})
	if err != nil {
		return "", err
	}
	return id, f.SaveReport(ctx, model.ReportMeta{ID: id, Title: "ISP outage evidence (sample)", From: from, To: to,
		Created: time.Now().Add(-time.Hour), Public: true, Bytes: len(body)}, body)
}

// ---------- baselines ----------

// fakeBaselines implements web.BaselineSource: each series' median, p95
// and loss over the backfilled history before the last hour (so the
// evening slowdown is not part of "normal").
type fakeBaselines struct {
	m map[model.SeriesKey]model.Baseline
}

func newFakeBaselines(ctx context.Context, st store.Reader, p *model.Profile, now time.Time, bf time.Duration) *fakeBaselines {
	fb := &fakeBaselines{m: map[model.SeriesKey]model.Baseline{}}
	from, to := now.Add(-bf), now.Add(-time.Hour)
	if !to.After(from) {
		return fb
	}
	for _, t := range p.Targets {
		for _, k := range kindsOf(t) {
			key := model.SeriesKey{Target: t.Name, Kind: k}
			var rtts []float64
			var lost int64
			_ = st.Raw(ctx, []model.SeriesKey{key}, from, to, func(rp store.RawPoint) error {
				switch {
				case rp.Lost && rp.Reason == model.ReasonGap:
				case rp.Lost:
					lost++
				default:
					rtts = append(rtts, rp.RTTms)
				}
				return nil
			})
			if len(rtts) < 20 {
				continue
			}
			sort.Float64s(rtts)
			n := int64(len(rtts))
			fb.m[key] = model.Baseline{Key: key, MedianMs: rtts[len(rtts)/2], P95Ms: rtts[len(rtts)*95/100],
				Loss: float64(lost) / float64(n+lost), Samples: n + lost, From: from, To: to}
		}
	}
	return fb
}

func (f *fakeBaselines) Get(key model.SeriesKey, _ time.Time) (model.Baseline, bool) {
	b, ok := f.m[key]
	return b, ok
}

// slow lists HTTPS series whose last 5 minutes are ≥1.5× their median.
func (f *fakeBaselines) slow(st store.Reader, p *model.Profile) func() []web.SlowTarget {
	var mu sync.Mutex
	var at time.Time
	var last []web.SlowTarget
	return func() []web.SlowTarget {
		mu.Lock()
		defer mu.Unlock()
		now := time.Now()
		if now.Sub(at) < 15*time.Second {
			return last
		}
		var keys []model.SeriesKey
		for _, t := range p.Targets {
			k := model.SeriesKey{Target: t.Name, Kind: model.KindHTTPS}
			if _, ok := f.m[k]; ok {
				keys = append(keys, k)
			}
		}
		res, err := st.Panel(context.Background(), store.PanelQuery{Keys: keys, From: now.Add(-5 * time.Minute), To: now, MaxPoints: 1})
		if err != nil {
			return last
		}
		var out []web.SlowTarget
		for _, c := range res.Series {
			var sum float64
			var n float64
			for i, m := range c.Mean {
				if i < len(c.N) && c.N[i] > 0 && !math.IsNaN(float64(m)) {
					sum += float64(m) * float64(c.N[i])
					n += float64(c.N[i])
				}
			}
			b := f.m[c.Key]
			if n == 0 || b.MedianMs <= 0 {
				continue
			}
			cur := sum / n
			if r := cur / b.MedianMs; r >= 1.5 {
				out = append(out, web.SlowTarget{Target: c.Key.Target, Kind: c.Key.Kind, Ratio: r, NowMs: cur, NormalMs: b.MedianMs})
			}
		}
		sort.Slice(out, func(i, j int) bool { return out[i].Ratio > out[j].Ratio })
		at, last = now, out
		return out
	}
}
